Update main.yml
test fetching var

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,6 +3,7 @@ name: "Coveralls"
 
 env:
       NODE_COVERALLS_DEBUG: 1
+      TESTCOVERAGE_THRESHOLD: 0
       
 jobs:
   coveralls:
@@ -23,4 +24,16 @@ jobs:
         uses: coverallsapp/github-action@v2
         with:
           path-to-lcov: coverage.lcov
+      - name: Quality Gate - Test coverage shall be above threshold
+        run: |
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Failed"
+                exit 1
+            fi
 
